In [1]:
import pandas as pd
from sqlalchemy import create_engine

The engine creates a Dialect object tailored towards PostgreSQL, as well as a Pool object which
 will establish a DBAPI connection at localhost:5432 when a connection request is first
 received. Note that the Engine and its underlying Pool do not establish the first actual
 DBAPI connection until the Engine.connect() method is called, or an operation which is
 dependent on this method such as Engine.execute() is invoked.
 In this way, Engine and Pool can be said to have a lazy initialization behavior

In [2]:
# Creating the engine
engine = create_engine('postgresql://postgres:l=den1TiFT@localhost:5432/dvdrental')

In [3]:
query1 = "SELECT * FROM actor;"  # String containing the SQL query to select all rows
# Import the data into DataFrame df
df_actor = pd.read_sql_query(query1, engine, parse_dates=['last_update'], index_col='last_update')  

query2 = "SELECT * FROM address;" 
df_address = pd.read_sql_query(query2, engine, parse_dates=['last_update'], index_col='last_update')  

query3 = "SELECT * FROM category;" 
df_category = pd.read_sql_query(query3, engine, parse_dates=['last_update'], index_col='last_update')

query4 = "SELECT * FROM city;"
df_city = pd.read_sql_query(query4, engine, parse_dates=['last_update'], index_col='last_update') 

query5 = "SELECT * FROM country;"  
df_country = pd.read_sql_query(query5, engine, parse_dates=['last_update'], index_col='last_update') 

query6 = "SELECT * FROM customer;"  
df_customer = pd.read_sql_query(query6, engine, parse_dates=['last_update'], index_col='last_update') 

query7 = "SELECT * FROM film;"  
df_film = pd.read_sql_query(query7, engine, parse_dates=['last_update'], index_col='last_update') 

query8 = "SELECT * FROM film_actor;"  
df_film_actor = pd.read_sql_query(query8, engine, parse_dates=['last_update'], index_col='last_update') 

query9 = "SELECT * FROM film_category;"  
df_film_category = pd.read_sql_query(query9, engine, parse_dates=['last_update'], index_col='last_update') 

query10 = "SELECT * FROM inventory;"  
df_inventory = pd.read_sql_query(query10, engine, parse_dates=['last_update'], index_col='last_update')  

query11 = "SELECT * FROM language;" 
df_actor = pd.read_sql_query(query11, engine, parse_dates=['last_update'], index_col='last_update') 

# Parse payment_date column as dates
query12 = "SELECT * FROM payment;"  
df_language = pd.read_sql_query(query12, engine, parse_dates=['payment_date'], index_col='payment_date') 
# Parse rental_date, return_date & last_update columns as dates
query13 = "SELECT * FROM rental;"  
df_rental = pd.read_sql_query(query13, engine, parse_dates=['rental_date','return_date','last_update'])

query14 = "SELECT * FROM staff;"  
df_staff = pd.read_sql_query(query14, engine, parse_dates=['last_update'], index_col='last_update') 

query15 = "SELECT * FROM store;"  
df_store = pd.read_sql_query(query15, engine, parse_dates=['last_update'], index_col='last_update')

In [8]:
df_customer.head()

,customer_id,store_id,first_name,last_name,email,address_id,activebool,create_date,active
last_update,,,,,,,,,
2013-05-26 14:49:45.738,524,1,Jared,Ely,jared.ely@sakilacustomer.org,530,True,2006-02-14,1
2013-05-26 14:49:45.738,1,1,Mary,Smith,mary.smith@sakilacustomer.org,5,True,2006-02-14,1
2013-05-26 14:49:45.738,2,1,Patricia,Johnson,patricia.johnson@sakilacustomer.org,6,True,2006-02-14,1
2013-05-26 14:49:45.738,3,1,Linda,Williams,linda.williams@sakilacustomer.org,7,True,2006-02-14,1
2013-05-26 14:49:45.738,4,2,Barbara,Jones,barbara.jones@sakilacustomer.org,8,True,2006-02-14,1

In [9]:
m_names = df_customer[df_customer['first_name'].str.contains("M")]
m_names

,customer_id,store_id,first_name,last_name,email,address_id,activebool,create_date,active
last_update,,,,,,,,,
2013-05-26 14:49:45.738,1,1,Mary,Smith,mary.smith@sakilacustomer.org,5,True,2006-02-14,1
2013-05-26 14:49:45.738,7,1,Maria,Miller,maria.miller@sakilacustomer.org,11,True,2006-02-14,1
2013-05-26 14:49:45.738,9,2,Margaret,Moore,margaret.moore@sakilacustomer.org,13,True,2006-02-14,1
2013-05-26 14:49:45.738,21,1,Michelle,Clark,michelle.clark@sakilacustomer.org,25,True,2006-02-14,1
2013-05-26 14:49:45.738,30,1,Melissa,King,melissa.king@sakilacustomer.org,34,True,2006-02-14,1
2013-05-26 14:49:45.738,38,1,Martha,Gonzalez,martha.gonzalez@sakilacustomer.org,42,True,2006-02-14,1
2013-05-26 14:49:45.738,44,1,Marie,Turner,marie.turner@sakilacustomer.org,48,True,2006-02-14,1
2013-05-26 14:49:45.738,60,1,Mildred,Bailey,mildred.bailey@sakilacustomer.org,64,True,2006-02-14,1
2013-05-26 14:49:45.738,80,1,Marilyn,Ross,marilyn.ross@sakilacustomer.org,84,True,2006-02-14,1
2013-05-26 14:49:45.738,128,1,Marjorie,Tucker,marjorie.tucker@sakilacustomer.org,132,True,2006-02-14,1
2013-05-26 14:49:45.738,131,2,Monica,Hicks,monica.hicks@sakilacustomer.org,135,True,2006-02-14,1
2013-05-26 14:49:45.738,151,2,Megan,Palmer,megan.palmer@sakilacustomer.org,155,True,2006-02-14,1
2013-05-26 14:49:45.738,154,2,Michele,Grant,michele.grant@sakilacustomer.org,158,True,2006-02-14,1
2013-05-26 14:49:45.738,178,2,Marion,Snyder,marion.snyder@sakilacustomer.org,182,True,2006-02-14,1
2013-05-26 14:49:45.738,188,1,Melanie,Armstrong,melanie.armstrong@sakilacustomer.org,192,True,2006-02-14,1
2013-05-26 14:49:45.738,223,1,Melinda,Fernandez,melinda.fernandez@sakilacustomer.org,227,True,2006-02-14,1
2013-05-26 14:49:45.738,226,2,Maureen,Little,maureen.little@sakilacustomer.org,230,True,2006-02-14,1
2013-05-26 14:49:45.738,236,1,Marcia,Dean,marcia.dean@sakilacustomer.org,240,True,2006-02-14,1
2013-05-26 14:49:45.738,239,2,Minnie,Romero,minnie.romero@sakilacustomer.org,243,True,2006-02-14,1
2013-05-26 14:49:45.738,240,1,Marlene,Welch,marlene.welch@sakilacustomer.org,244,True,2006-02-14,1
2013-05-26 14:49:45.738,246,1,Marian,Mendoza,marian.mendoza@sakilacustomer.org,250,True,2006-02-14,1
2013-05-26 14:49:45.738,252,2,Mattie,Hoffman,mattie.hoffman@sakilacustomer.org,256,True,2006-02-14,1
2013-05-26 14:49:45.738,254,2,Maxine,Silva,maxine.silva@sakilacustomer.org,259,True,2006-02-14,1
2013-05-26 14:49:45.738,256,2,Mabel,Holland,mabel.holland@sakilacustomer.org,261,True,2006-02-14,1
2013-05-26 14:49:45.738,257,2,Marsha,Douglas,marsha.douglas@sakilacustomer.org,262,True,2006-02-14,1
2013-05-26 14:49:45.738,258,1,Myrtle,Fleming,myrtle.fleming@sakilacustomer.org,263,True,2006-02-14,1
2013-05-26 14:49:45.738,267,1,Margie,Wade,margie.wade@sakilacustomer.org,272,True,2006-02-14,1
2013-05-26 14:49:45.738,285,1,Miriam,Mckinney,miriam.mckinney@sakilacustomer.org,290,True,2006-02-14,1
2013-05-26 14:49:45.738,292,2,Misty,Lambert,misty.lambert@sakilacustomer.org,297,True,2006-02-14,1
2013-05-26 14:49:45.738,293,2,Mae,Fletcher,mae.fletcher@sakilacustomer.org,298,True,2006-02-14,1
2013-05-26 14:49:45.738,302,1,Michael,Silverman,michael.silverman@sakilacustomer.org,307,True,2006-02-14,1
2013-05-26 14:49:45.738,312,2,Mark,Rinehart,mark.rinehart@sakilacustomer.org,317,True,2006-02-14,1
2013-05-26 14:49:45.738,323,2,Matthew,Mahan,matthew.mahan@sakilacustomer.org,328,True,2006-02-14,1
2013-05-26 14:49:45.738,383,1,Martin,Bales,martin.bales@sakilacustomer.org,388,True,2006-02-14,1
2013-05-26 14:49:45.738,403,1,Mike,Way,mike.way@sakilacustomer.org,408,True,2006-02-14,1
2013-05-26 14:49:45.738,408,1,Manuel,Murrell,manuel.murrell@sakilacustomer.org,413,True,2006-02-14,1
2013-05-26 14:49:45.738,413,2,Marvin,Yee,marvin.yee@sakilacustomer.org,418,True,2006-02-14,1
2013-05-26 14:49:45.738,422,1,Melvin,Ellington,melvin.ellington@sakilacustomer.org,427,True,2006-02-14,1
2013-05-26 14:49:45.738,441,1,Mario,Cheatham,mario.cheatham@sakilacustomer.org,446,True,2006-02-14,1
2013-05-26 14:49:45.738,444,2,Marcus,Hidalgo,marcus.hidalgo@sakilacustomer.org,449,True,2006-02-14,1
2013-05-26 14:49:45.738,445,1,Micheal,Forman,micheal.forman@sakilacustomer.org,450,True,2006-02-14,1
2013-05-26 14:49:45.738,448,1,Miguel,Betancourt,miguel.betancourt@sakilacustomer.org,453,True,2006-02-14,1
2013-05-26 14:49:45.738,482,1,Maurice,Crawley,maurice.crawley@sakilacustomer.org,487,True,2006-02-14,0
2013-05-26 14:49:45.738,499,2,Marc,Outlaw,marc.outlaw@sakilacustomer.org,504,True,2006-02-14,1
2013-05-26 14:49:45.738,508,2,Milton,Howland,milton.howland@sakilacustomer.org,513,True,2006-02-14,1
2013-05-26 14:49:45.738,520,2,Mitchell,Westmoreland,mitchell.westmoreland@sakilacustomer.org,526,True,2006-02-14,1
2013-05-26 14:49:45.738,539,1,Mathew,Bolin,mathew.bolin@sakilacustomer.org,545,True,2006-02-14,1
2013-05-26 14:49:45.738,553,1,Max,Pitt,max.pitt@sakilacustomer.org,559,True,2006-02-14,1
2013-05-26 14:49:45.738,576,2,Morris,Mccarter,morris.mccarter@sakilacustomer.org,582,True,2006-02-14,1
2013-05-26 14:49:45.738,583,1,Marshall,Thorn,marshall.thorn@sakilacustomer.org,589,True,2006-02-14,1
2013-05-26 14:49:45.738,588,1,Marion,Ocampo,marion.ocampo@sakilacustomer.org,594,True,2006-02-14,1